import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import Header from "./components/Header";
import CardListProduct from "./components/CardListProduct";
import Footer from "./components/Footer";

export default function Home() {
  return (
    <>
      <title>Shop</title>
      <meta name="description" content="Generated by Shop" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
      <Header />
      <div className="text-center m-20">
        <h1 className="text-3xl font-bold underline">Choose Color</h1>
        <div>
          <CardListProduct />
        </div>
      </div>
      <Footer />
    </>
  );
}
