import Head from "next/head";
import Image from "next/image";
import Header from "./components/Header";
import CardListProduct from "./components/CardListProduct";
import Footer from "./components/Footer";
import Banner from "../public/image/image.png";
import Rectangle from "../public/image/rect.png";
import Navbar from "./components/navbar";
import { useState } from "react";

const styles = {
  bannerContainer: {
    backgroundImage: `url(${Banner.src})`,
    height: "32rem",
  },
  buttonImg: {
    backgroundImage: `url(${Rectangle.src})`,
  },
};

export default function Home() {
  const [cari, setCari] = useState("");
  const [submit, setSubmit] = useState("");
  const handleSearch = () => {
    setSubmit(cari);
  };
  return (
    <>
      <title>Shop</title>
      <meta name="description" content="Generated by Shop" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
      {/* <Header /> */}
      <header>
        <Navbar />
        <div
          className="w-full bg-cover bg-center"
          style={styles.bannerContainer}
        >
          <div className="flex items-center justify-center h-full w-full bg-gray-900 bg-opacity-50">
            <div className="text-center">
              <h1 className="text-white text-2xl font-semibold uppercase md:text-3xl">
                Pilih warna favoritmu !
                <br />
                <span className="text-custom-blue-100 text-[20px]">
                  untuk penampilan terbaik
                </span>
              </h1>
              <div className="flex items-center mt-3">
                <input
                  className="h-10 w-full pl-4"
                  placeholder="Search"
                  onChange={(e) => setCari(e.target.value)}
                ></input>
                <button
                  className="h-10 w-[200px] text-white"
                  style={styles.buttonImg}
                  onClick={handleSearch}
                >
                  Cari Warna
                </button>
              </div>
            </div>
          </div>
        </div>
      </header>
      <div className="text-center m-10">
        {/* <div className="flex justify-center">
          <div className="flex justify-center p-5 rounded-md bg-white max-w-[800px] shadow-md">
            <div className="flex">
              <label className="flex items-center ml-10">
                <input type="checkbox" className="accent-java-blue w-4 h-4" />
                <span className="ml-4 text-java-blue">Customized</span>
              </label>
              <label className="flex items-center ml-10">
                <input type="checkbox" className="accent-java-blue w-4 h-4" />
                <span className="ml-4 text-java-blue">
                  Lengan panjang + RIB
                </span>
              </label>
              <label className="flex items-center ml-10">
                <input type="checkbox" className="accent-java-blue w-4 h-4" />
                <span className="ml-4 text-java-blue">
                  Lengan panjang Tanpa RIB
                </span>
              </label>
            </div>
          </div>
        </div> */}
        <div>
          {submit ? "Hasil Pencarian" + `"${submit}"` : ""}

          <CardListProduct search={submit} />
        </div>
      </div>
      <Footer />
    </>
  );
}
