import Navbar from "./components/navbar";
import CardListProduct from "./components/CardListProduct";
import Footer from "./components/Footer";
import Size from "../public/image/size.png";
import Model1 from "../public/image/model.svg";
import Model2 from "../public/image/model1.svg";
import Model3 from "../public/image/model2.svg";
import Image from "next/image";

export default function SizeChart() {
  return (
    <>
      <title>Shop</title>
      <meta name="description" content="Generated by Shop" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
      <Navbar />
      <Image src={Size} alt="" />
      <div className="text-center text-xl mt-4">Panduan Ukuran</div>
      <div className="flex justify-center">
        <div className="max-w-sm w-[1200px] lg:max-w-full lg:flex mt-4 mb-4">
          <div
            className="h-[500px] lg:h-[500px] lg:w-[400px] flex-none bg-cover rounded-t lg:rounded-t-none lg:rounded-l text-center overflow-hidden"
            style={{ backgroundImage: `url(${Model1.src})` }}
            title="Woman holding a mug"
          ></div>
          <div className="bg-white rounded-b lg:rounded-b-none lg:rounded-r p-4 flex flex-col justify-between leading-normal">
            <div className="p-2 ml-8 text-xl max-w-[100%] h-[100%] wrap-chart text-left pt-4">
              Lengan Pendek
              <div className="relative overflow-x-auto sm:rounded-lg pt-4">
                <table className="w-full text-sm text-left text-gray-500 dark:text-gray-400 ">
                  <thead className="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                    <tr>
                      <th scope="col" className="px-3 w-[225px] py-3">
                        Size
                      </th>
                      <th
                        scope="col"
                        className="px-3 w-[240px] py-3 text-blue-400 font-bold"
                      >
                        Panjang Atasan (cm)
                      </th>
                      <th
                        scope="col"
                        className="px-3 w-[240px] py-3 text-red-400 font-bold"
                      >
                        Lingkar Dada (cm)
                      </th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr className="bg-white border-b dark:bg-gray-900 dark:border-gray-700">
                      <th
                        scope="row"
                        className="px-3 py-2 font-medium text-gray-900 whitespace-nowrap dark:text-white"
                      >
                        XS
                      </th>
                      <td className="px-3 py-2 text-blue-400 font-bold">65</td>
                      <td className="px-3 py-2 text-red-400 font-bold">100</td>
                    </tr>
                    <tr className="border-b bg-gray-50 dark:bg-gray-800 dark:border-gray-700">
                      <th
                        scope="row"
                        className="px-3 py-2 font-medium text-gray-900 whitespace-nowrap dark:text-white"
                      >
                        S
                      </th>
                      <td className="px-3 py-2 text-blue-400 font-bold">67</td>
                      <td className="px-3 py-2 text-red-400 font-bold">102</td>
                    </tr>
                    <tr className="bg-white border-b dark:bg-gray-900 dark:border-gray-700">
                      <th
                        scope="row"
                        className="px-3 py-2 font-medium text-gray-900 whitespace-nowrap dark:text-white"
                      >
                        M
                      </th>
                      <td className="px-3 py-2 text-blue-400 font-bold">69</td>
                      <td className="px-3 py-2 text-red-400 font-bold">106</td>
                    </tr>
                    <tr className="border-b bg-gray-50 dark:bg-gray-800 dark:border-gray-700">
                      <th
                        scope="row"
                        className="px-3 py-2 font-medium text-gray-900 whitespace-nowrap dark:text-white"
                      >
                        L
                      </th>
                      <td className="px-3 py-2 text-blue-400 font-bold">71</td>
                      <td className="px-3 py-2 text-red-400 font-bold">110</td>
                    </tr>
                    <tr>
                      <th
                        scope="row"
                        className="px-3 py-2 font-medium text-gray-900 whitespace-nowrap dark:text-white"
                      >
                        XL
                      </th>
                      <td className="px-3 py-2 text-blue-400 font-bold">73</td>
                      <td className="px-3 py-2 text-red-400 font-bold">114</td>
                    </tr>
                    <tr className="border-b bg-gray-50 dark:bg-gray-800 dark:border-gray-700">
                      <th
                        scope="row"
                        className="px-3 py-2 font-medium text-gray-900 whitespace-nowrap dark:text-white"
                      >
                        XXL
                      </th>
                      <td className="px-3 py-2 text-blue-400 font-bold">75</td>
                      <td className="px-3 py-2 text-red-400 font-bold">118</td>
                    </tr>
                    <tr>
                      <th
                        scope="row"
                        className="px-3 py-2 font-medium text-gray-900 whitespace-nowrap dark:text-white"
                      >
                        XXXL
                      </th>
                      <td className="px-3 py-2 text-blue-400 font-bold">77</td>
                      <td className="px-3 py-2 text-red-400 font-bold">122</td>
                    </tr>
                    <tr className="border-b bg-gray-50 dark:bg-gray-800 dark:border-gray-700">
                      <th
                        scope="row"
                        className="px-3 py-2 font-medium text-gray-900 whitespace-nowrap dark:text-white"
                      >
                        XXXXL
                      </th>
                      <td className="px-3 py-2 text-blue-400 font-bold">79</td>
                      <td className="px-3 py-2 text-red-400 font-bold">126</td>
                    </tr>
                    <tr>
                      <th
                        scope="row"
                        className="px-3 py-2 font-medium text-gray-900 whitespace-nowrap dark:text-white"
                      >
                        XXXXXL
                      </th>
                      <td className="px-3 py-2 text-blue-400 font-bold">81</td>
                      <td className="px-3 py-2 text-red-400 font-bold">130</td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div className="flex justify-center">
        <div className="max-w-sm w-[1200px] lg:max-w-full lg:flex mt-4 mb-4">
          <div
            className="h-[500px] lg:h-[500px] lg:w-[400px] flex-none bg-cover rounded-t lg:rounded-t-none lg:rounded-l text-center overflow-hidden"
            style={{ backgroundImage: `url(${Model2.src})` }}
            title="Woman holding a mug"
          ></div>
          <div className="bg-white rounded-b lg:rounded-b-none lg:rounded-r p-4 flex flex-col justify-between leading-normal">
            <div className="p-2 ml-8 text-xl max-w-[100%] h-[100%] wrap-chart text-left pt-4">
              Lengan Panjang + RIB
              <div className="relative overflow-x-auto sm:rounded-lg pt-4">
                <table className="w-full text-sm text-left text-gray-500 dark:text-gray-400 ">
                  <thead className="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                    <tr>
                      <th scope="col" className="px-3 w-[225px] py-3">
                        Size
                      </th>
                      <th
                        scope="col"
                        className="px-3 w-[240px] py-3 text-blue-400 font-bold"
                      >
                        Panjang Atasan (cm)
                      </th>
                      <th
                        scope="col"
                        className="px-3 w-[240px] py-3 text-red-400 font-bold"
                      >
                        Lingkar Dada (cm)
                      </th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr className="bg-white border-b dark:bg-gray-900 dark:border-gray-700">
                      <th
                        scope="row"
                        className="px-3 py-2 font-medium text-gray-900 whitespace-nowrap dark:text-white"
                      >
                        XS
                      </th>
                      <td className="px-3 py-2 text-blue-400 font-bold">65</td>
                      <td className="px-3 py-2 text-red-400 font-bold">100</td>
                    </tr>
                    <tr className="border-b bg-gray-50 dark:bg-gray-800 dark:border-gray-700">
                      <th
                        scope="row"
                        className="px-3 py-2 font-medium text-gray-900 whitespace-nowrap dark:text-white"
                      >
                        S
                      </th>
                      <td className="px-3 py-2 text-blue-400 font-bold">67</td>
                      <td className="px-3 py-2 text-red-400 font-bold">102</td>
                    </tr>
                    <tr className="bg-white border-b dark:bg-gray-900 dark:border-gray-700">
                      <th
                        scope="row"
                        className="px-3 py-2 font-medium text-gray-900 whitespace-nowrap dark:text-white"
                      >
                        M
                      </th>
                      <td className="px-3 py-2 text-blue-400 font-bold">69</td>
                      <td className="px-3 py-2 text-red-400 font-bold">106</td>
                    </tr>
                    <tr className="border-b bg-gray-50 dark:bg-gray-800 dark:border-gray-700">
                      <th
                        scope="row"
                        className="px-3 py-2 font-medium text-gray-900 whitespace-nowrap dark:text-white"
                      >
                        L
                      </th>
                      <td className="px-3 py-2 text-blue-400 font-bold">71</td>
                      <td className="px-3 py-2 text-red-400 font-bold">110</td>
                    </tr>
                    <tr>
                      <th
                        scope="row"
                        className="px-3 py-2 font-medium text-gray-900 whitespace-nowrap dark:text-white"
                      >
                        XL
                      </th>
                      <td className="px-3 py-2 text-blue-400 font-bold">73</td>
                      <td className="px-3 py-2 text-red-400 font-bold">114</td>
                    </tr>
                    <tr className="border-b bg-gray-50 dark:bg-gray-800 dark:border-gray-700">
                      <th
                        scope="row"
                        className="px-3 py-2 font-medium text-gray-900 whitespace-nowrap dark:text-white"
                      >
                        XXL
                      </th>
                      <td className="px-3 py-2 text-blue-400 font-bold">75</td>
                      <td className="px-3 py-2 text-red-400 font-bold">118</td>
                    </tr>
                    <tr>
                      <th
                        scope="row"
                        className="px-3 py-2 font-medium text-gray-900 whitespace-nowrap dark:text-white"
                      >
                        XXXL
                      </th>
                      <td className="px-3 py-2 text-blue-400 font-bold">77</td>
                      <td className="px-3 py-2 text-red-400 font-bold">122</td>
                    </tr>
                    <tr className="border-b bg-gray-50 dark:bg-gray-800 dark:border-gray-700">
                      <th
                        scope="row"
                        className="px-3 py-2 font-medium text-gray-900 whitespace-nowrap dark:text-white"
                      >
                        XXXXL
                      </th>
                      <td className="px-3 py-2 text-blue-400 font-bold">79</td>
                      <td className="px-3 py-2 text-red-400 font-bold">126</td>
                    </tr>
                    <tr>
                      <th
                        scope="row"
                        className="px-3 py-2 font-medium text-gray-900 whitespace-nowrap dark:text-white"
                      >
                        XXXXXL
                      </th>
                      <td className="px-3 py-2 text-blue-400 font-bold">81</td>
                      <td className="px-3 py-2 text-red-400 font-bold">130</td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div className="flex justify-center">
        <div className="max-w-sm w-[1200px] lg:max-w-full lg:flex mt-4 mb-4">
          <div
            className="h-[500px] lg:h-[500px] lg:w-[400px] flex-none bg-cover rounded-t lg:rounded-t-none lg:rounded-l text-center overflow-hidden"
            style={{ backgroundImage: `url(${Model3.src})` }}
            title="Woman holding a mug"
          ></div>
          <div className="bg-white rounded-b lg:rounded-b-none lg:rounded-r p-4 flex flex-col justify-between leading-normal">
            <div className="p-2 ml-8 text-xl max-w-[100%] h-[100%] wrap-chart text-left pt-4">
              Lengan Panjang Tanpa RIB
              <div className="relative overflow-x-auto sm:rounded-lg pt-4">
                <table className="w-full text-sm text-left text-gray-500 dark:text-gray-400 ">
                  <thead className="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                    <tr>
                      <th scope="col" className="px-3 w-[225px] py-3">
                        Size
                      </th>
                      <th
                        scope="col"
                        className="px-3 w-[240px] py-3 text-blue-400 font-bold"
                      >
                        Panjang Atasan (cm)
                      </th>
                      <th
                        scope="col"
                        className="px-3 w-[240px] py-3 text-red-400 font-bold"
                      >
                        Lingkar Dada (cm)
                      </th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr className="bg-white border-b dark:bg-gray-900 dark:border-gray-700">
                      <th
                        scope="row"
                        className="px-3 py-2 font-medium text-gray-900 whitespace-nowrap dark:text-white"
                      >
                        XS
                      </th>
                      <td className="px-3 py-2 text-blue-400 font-bold">65</td>
                      <td className="px-3 py-2 text-red-400 font-bold">100</td>
                    </tr>
                    <tr className="border-b bg-gray-50 dark:bg-gray-800 dark:border-gray-700">
                      <th
                        scope="row"
                        className="px-3 py-2 font-medium text-gray-900 whitespace-nowrap dark:text-white"
                      >
                        S
                      </th>
                      <td className="px-3 py-2 text-blue-400 font-bold">67</td>
                      <td className="px-3 py-2 text-red-400 font-bold">102</td>
                    </tr>
                    <tr className="bg-white border-b dark:bg-gray-900 dark:border-gray-700">
                      <th
                        scope="row"
                        className="px-3 py-2 font-medium text-gray-900 whitespace-nowrap dark:text-white"
                      >
                        M
                      </th>
                      <td className="px-3 py-2 text-blue-400 font-bold">69</td>
                      <td className="px-3 py-2 text-red-400 font-bold">106</td>
                    </tr>
                    <tr className="border-b bg-gray-50 dark:bg-gray-800 dark:border-gray-700">
                      <th
                        scope="row"
                        className="px-3 py-2 font-medium text-gray-900 whitespace-nowrap dark:text-white"
                      >
                        L
                      </th>
                      <td className="px-3 py-2 text-blue-400 font-bold">71</td>
                      <td className="px-3 py-2 text-red-400 font-bold">110</td>
                    </tr>
                    <tr>
                      <th
                        scope="row"
                        className="px-3 py-2 font-medium text-gray-900 whitespace-nowrap dark:text-white"
                      >
                        XL
                      </th>
                      <td className="px-3 py-2 text-blue-400 font-bold">73</td>
                      <td className="px-3 py-2 text-red-400 font-bold">114</td>
                    </tr>
                    <tr className="border-b bg-gray-50 dark:bg-gray-800 dark:border-gray-700">
                      <th
                        scope="row"
                        className="px-3 py-2 font-medium text-gray-900 whitespace-nowrap dark:text-white"
                      >
                        XXL
                      </th>
                      <td className="px-3 py-2 text-blue-400 font-bold">75</td>
                      <td className="px-3 py-2 text-red-400 font-bold">118</td>
                    </tr>
                    <tr>
                      <th
                        scope="row"
                        className="px-3 py-2 font-medium text-gray-900 whitespace-nowrap dark:text-white"
                      >
                        XXXL
                      </th>
                      <td className="px-3 py-2 text-blue-400 font-bold">77</td>
                      <td className="px-3 py-2 text-red-400 font-bold">122</td>
                    </tr>
                    <tr className="border-b bg-gray-50 dark:bg-gray-800 dark:border-gray-700">
                      <th
                        scope="row"
                        className="px-3 py-2 font-medium text-gray-900 whitespace-nowrap dark:text-white"
                      >
                        XXXXL
                      </th>
                      <td className="px-3 py-2 text-blue-400 font-bold">79</td>
                      <td className="px-3 py-2 text-red-400 font-bold">126</td>
                    </tr>
                    <tr>
                      <th
                        scope="row"
                        className="px-3 py-2 font-medium text-gray-900 whitespace-nowrap dark:text-white"
                      >
                        XXXXXL
                      </th>
                      <td className="px-3 py-2 text-blue-400 font-bold">81</td>
                      <td className="px-3 py-2 text-red-400 font-bold">130</td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
      <Footer />
    </>
  );
}
